# Generated by Django 5.2.6 on 2025-11-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_sys', '0002_facility_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
