# Generated by Django 5.2.8 on 2025-11-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_sys', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
