# Generated by Django 5.2.8 on 2025-11-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_sys', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image_url', models.URLField(blank=True, help_text='Enter the URL of the hero banner image. Leave blank for default gradient.', null=True)),
                ('hero_title', models.CharField(default='Reserve football, volleyball and badminton courts instantly.', help_text='Main heading text for hero banner', max_length=200)),
                ('hero_subtitle', models.TextField(default='No more waiting in line or dealing with paper schedules. Book, manage and track your facility usage online.', help_text='Subtitle text for hero banner')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
