# Generated by Django 5.2.6 on 2025-11-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
