# Generated by Django 5.2.8 on 2025-11-27 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_sys', '0003_court_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityBlackout',
            fields=[
                ('facility_blackout_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('reason', models.TextField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackouts', to='booking_sys.facility')),
            ],
        ),
    ]
