# Generated by Django 5.2.8 on 2025-11-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_sys', '0006_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(default='support@unibook.edu', help_text='Email address for support inquiries', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_phone',
            field=models.CharField(default='+230 800 1234', help_text='Phone number for support (format: +country code XXX XXXX)', max_length=20),
        ),
    ]
